### ISSUE TITLE
已找到问题

### ISSUE THREAD

**Issue by NBIronman** [rongchenlin/LibraryManagementSystem#1]
1

**Comment by rongchenlin** [comment]
应该是UTF-8&nbsp;
Unicode。
你可以先尝试一下。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月18日(周六) 晚上10:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rongchenlin/LibraryManagementSystem] 运行SQL脚本失败 (Issue #1)




 
麻烦问下您。您使用的SQL脚本文件所对应的数据库编码字符集和排列规则方式都是什么？我导入SQL文件每次都是失败。
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rongchenlin** [comment]
应该是UTF-8 Unicode，排序规则应该不选好像也可以。你可以尝试使用navicat导入试试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月18日(周六) 晚上10:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rongchenlin/LibraryManagementSystem] 运行SQL脚本失败 (Issue #1)




 
麻烦问下您。您使用的SQL脚本文件所对应的数据库编码字符集和排列规则方式都是什么？我导入SQL文件每次都是失败。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
